# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title.html

title : Angelo Vargas
tagline: Site Tagline

links: 
  - name: About
    url: /about.html
  - name: Blog
    url: /index.html
  - name: English
    url: /en.html
  - name: Español
    url: /es.html
  - name: Twitter
    url: http://twitter.com/trukin
  - name: GitHub
    url: http://github.com/avargas
  - name: LinkedIn
    url: http://www.linkedin.com/in/angelovargas